word2vec_file: './data/raw_files/GoogleNews-vectors-negative300.bin'
log_reg_model_filename: './models/trained_models/word2vecLogisticRegression.joblib'
preprocessed_df_filename: './preprocessing/saved_dataframe/preprocessed_df.pkl'
LSTM_filename: './models/trained_models/word2vec_LSTM.keras'
lightGBM_filename: './models/trained_models/word2vec_lightGBM.joblib'

mispell_dict:
  'colour': 'color'
  'centre': 'center'
  'didnt': 'did not'
  'doesnt': 'does not'
  'isnt': 'is not'
  'shouldnt': 'should not'
  'wasnt' : 'was not'
  'hasnt' : 'has not'
  'Couldn' : 'could not'
  'aint' : 'am not'
  'yeahh' : 'yeah'
  'heyy' : 'hey'
  'favourite': 'favorite'
  'travelling': 'traveling'
  'counselling': 'counseling'
  'theatre': 'theater'
  'cancelled': 'canceled'
  'labour': 'labor'
  'organisation': 'organization'
  'wwii': 'world war 2'
  'citicise': 'criticize'
  'realise' : 'realize'
  'realised': 'realized'
  'instagram': 'social medium'
  'whatsapp': 'social medium'
  'snapchat': 'social medium'
  'tweetdeck': 'social medium'
  'lt3': 'love'    
  'lt##': 'love'
  'love#': 'love'
  'grey' : 'gray'
  'tmr' : 'tomorrow'
  'arse' : 'ass'
  'ahah' : 'lol'
  'awh' : 'aww'
  'youuu' : 'you'
  'ughhh' : 'ugh'
  'tomorroww' : 'tomorrow'

selected_stop_words: 
  - 'a'
  - 'to'
  - 'of'
  - 'and'

                